/*
** vim: ts=4 sw=4 et
*/
#include <stdio.h>
#include <stdlib.h>

/*
** This header file is part of the stand-alone interface.
** It contains declarations for mercury_init() and mercury_terminate(),
** which are used to respectively start and shutdown the Mercury runtime.
*/
#include "mercury_lib_int.h"

/*
** mercury_lib.mh is generated by the compiler when we build libmercury_lib.
** It contains declarations for procedures exported by pragma foreign_export
** as well as other exported entities, like mutables.
**
*/
#include "mercury_lib.mh"

typedef MR_Word MR_AtomStore;
typedef MR_Word MR_IntList;
typedef MR_Word MR_FloatList;

static void print_ints(MR_IntList);
static void print_floats(MR_FloatList);

int
main(int argc, char **argv)
{
    void *stack_bottom;

    MR_AtomStore atomstore;
    MR_IntList keys;
    MR_FloatList objs;


    /* Before calling any Mercury procedures we must first initialise
    ** the Mercury runtime, standard library and any other Mercury libraries
    ** that we will be using.  The function mercury_init() is used to do
    ** this.  In order it does the following:
    **
    ** (1) initialises the runtime
    ** (2) initialises the standard library
    ** (3) calls any predicates specified in `:- initialise' declarations
    **     and assigns any mutables their initial value   
    **
    ** We strongly recommend that calling this function is the first thing
    ** that your program does.
    **
    ** The third argument to mercury_init() is address of the base of the
    ** stack.  In grades that support conservative GC is used tell the
    ** collector where to begin tracing.
    */
    mercury_init(argc, argv, &stack_bottom);

    /*
    ** Here is a call to an exported Mercury procedure that does some I/O.
    */

    makevars(&atomstore,&keys,&objs);

    print_ints(keys);
    print_floats(objs);

    usevars(atomstore);

    /*
    ** Once we have finished calling Mercury procedures then we shut
    ** down the Mercury runtime by calling the function
    ** mercury_terminate().  The value returned by this function 
    ** is Mercury's exit status (as set by io.set_exit_status/3.)
    **
    ** This function will also invoke any finalisers specified in
    ** `:- finalise' declarations in the set of Mercury libraries that
    ** we are using.
    */
    return mercury_terminate();
}

static void print_ints(MR_IntList list) {
	if (MR_list_is_empty(list)) {
		printf("[]");
	} else {
		printf("[");
		printf("%d", MR_list_head(list));
		list = MR_list_tail(list);
		while (!MR_list_is_empty(list)) {
			printf(", %d",  MR_list_head(list));
			list = MR_list_tail(list);
		}
		printf("]");
	}
}

static void print_floats(MR_FloatList list) {
	if (MR_list_is_empty(list)) {
		printf("[]");
	} else {
		printf("[");
		printf("%f", MR_word_to_float(MR_list_head(list)));
		list = MR_list_tail(list);
		while (!MR_list_is_empty(list)) {
			printf(", %f",  MR_list_head(list));
			list = MR_list_tail(list);
		}
		printf("]");
	}
}
