/*
** mercury_lib.mh is generated by the compiler when we build libmercury_lib.
** It contains declarations for procedures exported by pragma foreign_export
** as well as other exported entities, like mutables.
**
*/
#include "mfoilp.mh"

typedef MR_Word MR_AtomStore;
typedef MR_Word MR_IntList;
typedef MR_Word MR_FloatList;
typedef MR_Word MR_StringList;
typedef MR_Word MR_FloatListList;
typedef MR_Word MR_IntListList;
typedef MR_Word MR_ConsStore;
